# disk
target_disk: /dev/vdb
pool_size: 7900G
lv_size: 7850G
vg_name: vg_cluster
default_mode: u=rwX,g=rwX,o=rwX,g+s
metrics:
  enabled: true
highavailability:
  enabled: true
  dns: "storage.localdomain"
  vip: "10.0.0.50"
  cidr: 16
  user: "hacluster"
  pass: "password"
  bindnet: "10.0.0.0"
samba_users:
- user: "dummy1"
  pass: "pass1"
target_volumes:
- name: "storage"
  nfs: true
  smb: true
  redundancy: 2
  smb_options:
    "browsable": "yes"
    "guest ok": "yes"
    "path": "/"
    "read only": "no"
    "writable": "yes"
    "force user": "{{ nobody_user }}"
    "force group": "{{ nobody_group }}"
    "guest only": "yes"
    "directory mode": "0777"
    "create mode": "0666"
- name: "critical"
  smb: true
  nfs: true
  smb_options:
    "browsable": "yes"
    "guest ok": "yes"
    "path": "/"
    "read only": "no"
    "writable": "yes"
    "force user": "{{ nobody_user }}"
    "force group": "{{ nobody_group }}"
    "guest only": "yes"
    "directory mode": "0777"
    "create mode": "0666"
- name: "media"
  smb: true
  nfs: true
  redundancy: 3
  smb_options:
    "browsable": "yes"
    "guest ok": "yes"
    "path": "/"
    "read only": "no"
    "writable": "yes"
    "force user": "{{ nobody_user }}"
    "force group": "{{ nobody_group }}"
    "guest only": "yes"
    "directory mode": "0777"
    "create mode": "0666"
- name: "nc_media"
  nfs: true
  smb: true
  smb_options:
    "browsable": "yes"
    "guest ok": "yes"
    "path": "/"
    "read only": "no"
    "writable": "yes"
    "force user": "{{ nobody_user }}"
    "force group": "{{ nobody_group }}"
    "guest only": "yes"
    "directory mode": "0777"
    "create mode": "0666"
- name: "bulk"
  smb: true
  nfs: true
  smb_options:
    "browsable": "yes"
    "guest ok": "yes"
    "path": "/"
    "read only": "no"
    "writable": "yes"
    "force user": "{{ nobody_user }}"
    "force group": "{{ nobody_group }}"
    "guest only": "yes"
    "directory mode": "0777"
    "create mode": "0666"
- name: "home"
  redundancy: 3 
  mode: u=rwX,g=rwX,o=
  nfs: false
  smb: true
  smb_options:
    "browsable": "yes"
    "guest ok": "no"
    "path": "/%U"
    "read only": "no"
    "writable": "yes"
    "valid users": "%U"
    "directory mode": "0770"
    "create mode": "0660"
    "force group": "{{ nobody_group }}"
- name: "config"
  mount: false
  redundancy: 3
