---
- name: "restart glusterd"
  service:
    name: "{{ gluster_service_name }}"
    state: restarted

- name: "restart nfs-ganesha"
  service:
    name: nfs-ganesha
    state: restarted
  when: not highavailability.enabled

- name: "restart smb"
  service:
    name: "{{ smb_service }}"
    state: restarted
  when: not highavailability.enabled

- name: "restart nmb"
  service:
    name: "{{ nmb_service }}"
    state: restarted
  when: not highavailability.enabled

- name: "restart pcsd"
  service:
    name: pcsd
    state: restarted

- name: "restart corosync"
  service:
    name: corosync
    state: restarted

- name: "restart pacemaker"
  service:
    name: pacemaker
    state: restarted

- name: "restart node_exporter"
  service:
    name: node_exporter
    state: restarted
