---
# this is a complete mess because i had to keep opening ports
# to get things to work and wasn't really good about tracking why
# turns out that adding services for things doesn't always open the
# right ports or _all_ of the right ports. need to clean this up but
# honestly isn't that critical
- name: Open Firewall for clients
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
  - "22/tcp"
  - "111/tcp"
  - "139/tcp"
  - "445/tcp"
  - "875/tcp"
  - "662/tcp"
  - "662/udp"
  - "892/tcp"
  - "892/udp"
  - "965/tcp"
  - "2049/tcp"
  - "32803/tcp"
  - "32769/udp"
  - "38465-38469/tcp"
  - "38000-44000/tcp"
  - "631/tcp"
  - "111/udp"
  - "875/udp"
  - "963/udp"
  - "49140-49260/tcp"
  - "24007-24009/tcp"
  - "24009/tcp"
  - "33401/tcp"
  - "39299/tcp"
  - "44055/udp"
  - "33167/tcp"
  - "2049/tcp"
  - "2049/udp"
  - "875/tcp"      
  - "875/udp"
  - "44431/tcp"
  - "44431/udp"
  - "35033/tcp"
  - "41148/udp"
  - "42365/tcp"

- name: Open Firewall services for clients
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
  - "nfs"
  - "rpc-bind"
  - "mountd"
  - "samba"
  - "samba-client"
