---
# from: http://docs.grafana.org/installation/rpm/

# install grafana repo
- name: Add grafana repo template
  template:
    src: grafana.repo.j2
    dest: /etc/yum.repos.d/grafana.repo

# install grafana
- name: Install grafana from repo
  yum:
    name: grafana
    state: latest
  notify:
  - restart grafana    
