---
- include_tasks: "grafana-redhat.yml"
  when: ansible_os_family | lower == "redhat"

- include_tasks: "grafana-ubuntu.yml"
  when: ansible_distribution | lower == "ubuntu"

- name: Create shared configuration folder for Grafana (cheap HA)
  file:
    path: "/opt/config/{{ item }}"
    owner: grafana
    group: grafana
    state: directory
    mode: "u=rwX,g=rwX,o=rX"
  with_items:
  - "grafana"
  - "grafana/plugins"    
  - "grafana/sessions"

- name: Process Grafana template
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
  - restart grafana

- name: Overwrite data dir on Ubunut
  lineinfile:
    path: /etc/default/grafana-server
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  when: ansible_distribution | lower == "ubuntu"  
  with_items:
    - regexp: "^DATA_DIR=.+$"
      line: "DATA_DIR=/opt/config/grafana"
    - regexp: "^PLUGINS_DIR=.+$"
      line: "PLUGINS_DIR=/opt/config/grafana/plugins"
  notify:
  - restart grafana

- name: Open external Grafana port
  firewalld:
    zone: public
    port: "80/tcp"
    state: enabled
    permanent: true
    immediate: true

- name: Redirect port to Grafana on 3000
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    rich_rule: "rule family=ipv4 forward-port port=80 protocol=tcp to-port=3000"

- name: Ensure Grafana service is started
  service:
    name: grafana-server
    enabled: true
    state: started
