---
# taken from http://docs.grafana.org/installation/debian/#apt-repository
- name: Add apt signing key from packagecloud
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Add debian/ubuntu apt repo
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
    state: present

- name: Update APT cache and install grafana
  apt:
    name: grafana
    state: latest
    update_cache: true

- name: Add grafana user
  user:
    name: grafana
    group: grafana    