---
- include: facts.yml
  tags:
    - always

- include: pre.yml
  tags:
    - pre

- include: disks.yml
  tags:
    - disks

- include: firewall.yml
  tags:
    - firewall

- include: gluster.yml
  tags:
    - gluster

- include: sharing.yml
  tags:
    - sharing
    - nfs
    - samba

# node_exporter for remote metrics scraping
- include: metrics.yml
  tags: 
  - metrics
  when: metrics.enabled

# do HA tasks when ha is explicitly enabled
- include: ha.yml
  tags:
    - ha
  when: highavailability.enabled
