---
- name: Create override dir for NFS-ganesha service
  file:
    path: /etc/systemd/system/nfs-ganesha.service.d
    state: directory

- name: Override service for NFS-ganesha
  template:
    src: nfs-ganesha-override.conf.j2
    dest: /etc/systemd/system/nfs-ganesha.service.d/10-override.conf
  notify:
  - "restart nfs-ganesha"
  
- name: Configure NFS Ganesha main configuration
  template:
    src: ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
  notify:
    - "restart nfs-ganesha"
    - "restart glusterd"

- name: Ensure export folder exists for ganesha configuration
  file:
    path: /etc/ganesha/exports
    state: directory

- name: Configure NFS Ganesha exports for target volumes
  template:
    src: export.target_volume_name.conf.j2
    dest: /etc/ganesha/exports/export.{{ item.1.name }}.conf
  vars:
    target_volume_id: "{% if item.1.id is defined %}{{ item.1.id }}{% else %}{{ item.0 + 1000 }}{% endif %}" # volume id should always be > 0, a 0 ID won't be exported
    target_volume_name: "{{ item.1.name }}"
  with_indexed_items: "{{ target_volumes }}"
  when: item.1.exported
  notify:
  - "restart nfs-ganesha"

- name: Ensure nfs-ganesha wants gluster
  command: "systemctl add-requires nfs-ganesha.service {{ gluster_service_name }}.service"
  args:
    creates: "/etc/systemd/system/nfs-ganesha.service.requires/glusterd.service"

- name: Start NFS Ganesha service
  service:
    name: nfs-ganesha
    state: started
    enabled: true
  notify:
  - "restart glusterd"

